documentation:
  - changed-files:
      - any-glob-to-any-file:
          - README.md
          - docs/**

github-actions:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**

resume:
  - changed-files:
      - any-glob-to-any-file:
          - "*.html"
          - "*.css"
          - "*.js"
          - education/**
          - projects/**
          - work/**

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - package.json
          - package-lock.json
          - requirements.txt
